# Generated by Django 4.1.7 on 2023-06-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_rename_email_serviceuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('singer_name', models.CharField(max_length=250)),
                ('song', models.FileField(max_length=250, upload_to='songs/')),
                ('songs_image', models.FileField(default=None, max_length=250, null=True, upload_to='song-photo/')),
                ('privacy', models.CharField(max_length=15)),
                ('users_email', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
