# Generated by Django 4.1.7 on 2023-06-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_songs_alter_serviceuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='songs_image',
            field=models.FileField(default=None, null=True, upload_to='song-photo/'),
        ),
    ]
