# Generated by Django 4.1.7 on 2023-06-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_alter_songs_song_alter_songs_songs_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='user_id',
            new_name='userId',
        ),
    ]
