# Generated by Django 4.1.7 on 2023-06-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_rename_user_id_songs_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
