# Generated by Django 4.1.7 on 2023-06-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0007_rename_songs_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
