# Generated by Django 4.1.7 on 2023-06-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0009_alter_song_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSong',
            fields=[
                ('shareId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('songId', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='userId',
            new_name='songId',
        ),
        migrations.AlterField(
            model_name='song',
            name='users_email',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
