# Generated by Django 4.1.7 on 2023-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0010_sharedsong_rename_userid_song_songid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedsong',
            name='songId',
        ),
        migrations.AddField(
            model_name='sharedsong',
            name='songName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
