# Generated by Django 4.1.7 on 2023-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0011_remove_sharedsong_songid_sharedsong_songname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedsong',
            name='sharedBy',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
