# Generated by Django 4.1.7 on 2023-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0012_sharedsong_sharedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedsong',
            name='singer_name',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedsong',
            name='song',
            field=models.FileField(default=None, max_length=250, upload_to='protected-songs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedsong',
            name='songs_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='protected-songs-photo/'),
        ),
    ]
