# Generated by Django 4.1.7 on 2023-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0013_sharedsong_singer_name_sharedsong_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedsong',
            name='song',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='protected-songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='songs/'),
        ),
    ]
